version: "3.7"
services:
  web:
    build: ./web
    ports:
      - "3000:3000"
    volumes:
      - "./web:/app"
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - "./api:/app"
