version: "3.6"
services:
  web:
    build: ./web
    ports:
      - "80:3000"
    volumes:
      - "./web:/app"
    restart: always
  api:
    build: ./api
    ports:
      - "4000:4000"
    volumes:
      - "./api:/app"
    restart: always
    environment:
      - PGUSER=dev
      - PGHOST=rdb
      - PGPASSWORD=dev
      - PGDATABASE=resin
      - PGPORT=5432
      - JWT_SECRET=xS2T22oigo9PIJ9dfW
      - GRAPGQL_PORT=4000
  rdb:
    image: postgres:11
    ports:
      - "5432:5432"
    volumes:
      - "./temp/pg:/var/lib/postgresql/data"
    restart: always
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5555:80"
    environment:
      - PGADMIN_DEFAULT_EMAIL=dev
      - PGADMIN_DEFAULT_PASSWORD=dev
